import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { UserContextProvider } from "@/utils/contexts";
import LoginWrapper from "@/components/LoginWrapper";
import Header from "@/components/Header";
import Navigation from "@/components/Navigation";
import Footer from "@/components/Footer";
import { ThemeProvider, CssBaseline, createTheme } from "@mui/material";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={"min-h-screen bg-gradient-to-b from-orange-50 via-amber-50 to-white"}
      >

        <UserContextProvider>
          <Header />
          <LoginWrapper>
            <Navigation />
            {children}
            <Footer/>
          </LoginWrapper>
        </UserContextProvider>
      </body>
    </html>
  );
}
